name: e_commerse_application
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  fluttertoast: ^8.2.2
  flutter_screenutil: ^5.8.4
  zoom_tap_animation: ^1.1.0
  like_button: ^2.0.5
  sqflite: ^2.2.8+4
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
